"""
Script to generate LaTeX code for including generated figures in the book
"""

import os
from pathlib import Path

def generate_latex_figure_includes():
    """Generate LaTeX code for including figures"""
    from pathlib import Path
    
    # Get project root (parent of scripts directory)
    project_root = Path(__file__).parent.parent
    figures_dir = project_root / "results" / "figures"
    if not figures_dir.exists():
        print("Figures directory not found. Run research_data_collection.py first.")
        return
    
    # Map figure files to LaTeX labels
    figure_mapping = {
        'market_share_pie.png': {
            'label': 'fig:market_share_pie',
            'caption_en': 'German Food Retail Market Share Distribution',
            'caption_de': 'Marktanteilsverteilung im deutschen Lebensmitteleinzelhandel',
            'caption_zh': '德国食品零售市场份额分布'
        },
        'revenue_trend.png': {
            'label': 'fig:revenue_trend',
            'caption_en': 'Edeka Revenue Trend (2019-2023)',
            'caption_de': 'Edeka Umsatztrend (2019-2023)',
            'caption_zh': '艾德卡收入趋势（2019-2023）'
        },
        'efficiency_metrics.png': {
            'label': 'fig:efficiency_metrics',
            'caption_en': 'Efficiency Metrics: Revenue per Employee and Store',
            'caption_de': 'Effizienzkennzahlen: Umsatz pro Mitarbeiter und Filiale',
            'caption_zh': '效率指标：每员工和每门店收入'
        },
        'competitive_comparison.png': {
            'label': 'fig:competitive_comparison',
            'caption_en': 'Competitive Comparison: Market Share and Revenue',
            'caption_de': 'Wettbewerbsvergleich: Marktanteil und Umsatz',
            'caption_zh': '竞争比较：市场份额和收入'
        },
        'store_distribution.png': {
            'label': 'fig:store_distribution',
            'caption_en': 'Store Count Comparison (Top 5 Competitors)',
            'caption_de': 'Filialanzahl-Vergleich (Top 5 Konkurrenten)',
            'caption_zh': '门店数量比较（前5名竞争对手）'
        },
        'growth_analysis.png': {
            'label': 'fig:growth_analysis',
            'caption_en': 'Year-over-Year Growth Rates',
            'caption_de': 'Jahreswachstumsraten',
            'caption_zh': '同比增长率'
        }
    }
    
    latex_code = []
    latex_code.append("% Auto-generated LaTeX figure includes")
    latex_code.append("% Generated by figure_integration.py")
    latex_code.append("%")
    latex_code.append("% To use these figures in your LaTeX document:")
    latex_code.append("% 1. Copy the figure files to your book/figures/ directory")
    latex_code.append("% 2. Include the relevant \\input{} command in your chapter")
    latex_code.append("")
    
    for filename, info in figure_mapping.items():
        if (figures_dir / filename).exists():
            latex_code.append(f"% Figure: {filename}")
            latex_code.append("\\begin{figure}[h]")
            latex_code.append("\\centering")
            latex_code.append(f"\\includegraphics[width=0.9\\textwidth]{{figures/{filename}}}")
            latex_code.append(f"\\caption{{{info['caption_en']} / {info['caption_de']} / {info['caption_zh']}}}")
            latex_code.append(f"\\label{{{info['label']}}}")
            latex_code.append("\\end{figure}")
            latex_code.append("")
    
    # Write to file
    project_root = Path(__file__).parent.parent
    output_file = project_root / "results" / "figures_latex_code.tex"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(latex_code))
    
    print(f"✓ Generated LaTeX code: {output_file}")
    print(f"\nTo use in your book:")
    print(f"1. Copy figures from results/figures/ to book/figures/")
    print(f"2. Add \\graphicspath{{{{figures/}}}} to your main.tex")
    print(f"3. Use the generated LaTeX code in your chapters")

if __name__ == "__main__":
    generate_latex_figure_includes()
